# services:
#   projectsManagement:
#     image: mongo:5.0.0
#     container_name: projects_management_database
#     ports:
#       - 27017:27017
#     volumes:
#       - ./mongo:/data/db

version: '3'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: projects-management
    volumes:
      - ./mongo:/data/db